server:
  port: 8085

spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8083"
  cloud:
    gateway:
      routes:
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/customer/**
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/account/**

eureka:
  instance:
    hostname: localhost
    instance-id: localhost:api-gateway:8085
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8081/eureka

management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info
