server:
  port: 8083

spring:
  application:
    name: config-server
  profiles:
    active: native

eureka:
  instance:
    hostname: localhost
    instance-id: localhost::config-server:8083
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8081/eureka