server:
  port: 8084

eureka:
  instance:
    hostname: localhost
    instance-id: localhost:account-service:8084
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8081/eureka