server:
  port: 8082

eureka:
  instance:
    hostname: localhost
    instance-id: localhost:customer-service:8082
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8081/eureka